package seed

import (
	"time"

	"matchit/backend/api/internal/model"
)

// Posts 与 Flutter mockPosts 对齐，便于 POST /api/v1/seed 一键导入
func Posts(now time.Time) []model.MatchPost {
	return []model.MatchPost{
		{
			ID:               "board_official_1",
			Title:            "【官方】MATCHit 桌游嘉年华 · 本周末",
			Description:      "平台官方活动，多桌游同场，报名即送周边。",
			CurrentMembers:   12,
			MaxMembers:       30,
			Area:             "BoardGames",
			Tab:              "推荐",
			HardcoreScore:    55,
			HostFaceTraits:   []string{"策略思维", "桌游爱好者", "社交型", "平衡型"},
			InteractionCount: 890,
			LastActiveTime:   now.Add(-1 * time.Hour),
			MatchScore:       78,
			HostNickname:     "MATCHit 官方",
			HostCreditScore:  99,
			EventDateTime:    now.Add(2*24*time.Hour + 14*time.Hour),
			EventLocation:    "上海市徐汇区 MATCHit 体验中心",
			IsPinned:         true,
			PinPriority:      100,
		},
		{
			ID:               "board_1",
			Title:            "周六下午寻找《阿瓦隆》大神局",
			Description:      "想约一组 5 人局，必须是硬核老手。",
			CurrentMembers:   3,
			MaxMembers:       5,
			Area:             "BoardGames",
			Tab:              "推荐",
			HardcoreScore:    95,
			HostFaceTraits:   []string{"策略思维", "硬核派", "逻辑型", "竞争意识"},
			InteractionCount: 420,
			LastActiveTime:   now.Add(-6 * time.Hour),
			MatchScore:       40,
			HostNickname:     "阿瓦隆老司机",
			HostCreditScore:  92,
			EventDateTime:    now.Add(24*time.Hour + 15*time.Hour),
			EventLocation:    "上海市长宁区桌游吧 · 愚园路店",
		},
		{
			ID:               "board_2",
			Title:            "周五晚桌游《卡坦》进阶局",
			Description:      "熟悉规则，氛围轻松。",
			CurrentMembers:   2,
			MaxMembers:       4,
			Area:             "BoardGames",
			Tab:              "桌游",
			HardcoreScore:    55,
			HostFaceTraits:   []string{"策略思维", "桌游爱好者", "平衡型", "团队配合"},
			InteractionCount: 256,
			LastActiveTime:   now.Add(-12 * time.Hour),
			MatchScore:       60,
			HostNickname:     "卡坦岛民",
			HostCreditScore:  86,
			EventDateTime:    now.Add(3*24*time.Hour + 19*time.Hour),
			EventLocation:    "上海市静安区社区活动中心 3F",
		},
		{
			ID:               "board_3",
			Title:            "周五晚桌游《卡坦》新手局",
			Description:      "新朋友优先，氛围轻松，地点靠近地铁站。",
			CurrentMembers:   2,
			MaxMembers:       4,
			Area:             "BoardGames",
			Tab:              "桌游",
			HardcoreScore:    20,
			HostFaceTraits:   []string{"桌游爱好者", "休闲派", "社交型", "慢节奏"},
			InteractionCount: 98,
			LastActiveTime:   now.Add(-3 * 24 * time.Hour),
			MatchScore:       20,
			HostNickname:     "慢热桌游君",
			HostCreditScore:  78,
			EventDateTime:    now.Add(4*24*time.Hour + 20*time.Hour),
			EventLocation:    "上海市普陀区金沙江路地铁站附近",
		},
		{
			ID:               "food_1",
			Title:            "周末附近美食探店拼餐",
			Description:      "想找 4 人拼餐，吃遍市区新开餐厅。",
			CurrentMembers:   3,
			MaxMembers:       4,
			Area:             "Food",
			Tab:              "附近",
			HardcoreScore:    30,
			HostFaceTraits:   []string{"美食探索", "社交型", "慢节奏", "拍照打卡"},
			InteractionCount: 180,
			LastActiveTime:   now.Add(-20 * time.Hour),
			MatchScore:       35,
			HostNickname:     "吃货小分队",
			HostCreditScore:  84,
			EventDateTime:    now.Add(2*24*time.Hour + 12*time.Hour),
			EventLocation:    "上海市黄浦区新天地商圈",
		},
		{
			ID:               "sport_1",
			Title:            "周日早晨街头篮球 3v3",
			Description:      "附近友邻一起玩，装备齐全，轻松娱乐。欢迎热爱运动的你加入。",
			CurrentMembers:   5,
			MaxMembers:       5,
			Area:             "Sport",
			Tab:              "附近",
			HardcoreScore:    40,
			HostFaceTraits:   []string{"运动达人", "活力型", "竞争意识", "早起党"},
			InteractionCount: 310,
			LastActiveTime:   now.Add(-24 * time.Hour),
			MatchScore:       25,
			HostNickname:     "球场老炮",
			HostCreditScore:  88,
			EventDateTime:    now.Add(5*24*time.Hour + 8*time.Hour),
			EventLocation:    "上海市浦东新区张江社区篮球场",
		},
		{
			ID:               "board_4",
			Title:            "#狼人杀 缺4人",
			Description:      "今晚 8 点开局，有法官，新手可带，氛围欢乐不贴脸。",
			CurrentMembers:   4,
			MaxMembers:       8,
			Area:             "BoardGames",
			Tab:              "桌游",
			HardcoreScore:    35,
			HostFaceTraits:   []string{"狼人杀", "桌游", "欢乐局", "周末夜"},
			InteractionCount: 512,
			LastActiveTime:   now.Add(-45 * time.Minute),
			MatchScore:       72,
			HostNickname:     "法官小姐姐",
			HostCreditScore:  91,
			EventDateTime:    now.Add(6 * time.Hour),
			EventLocation:    "上海市杨浦区大学路剧本杀馆",
		},
		{
			ID:               "board_5",
			Title:            "剧本杀《年轮》拼车 · 差2女",
			Description:      "情感本，6人本，已有4人，希望不跳车、能沉浸。",
			CurrentMembers:   4,
			MaxMembers:       6,
			Area:             "BoardGames",
			Tab:              "推荐",
			HardcoreScore:    60,
			HostFaceTraits:   []string{"剧本杀", "情感本", "沉浸", "桌游"},
			InteractionCount: 367,
			LastActiveTime:   now.Add(-3 * time.Hour),
			MatchScore:       55,
			HostNickname:     "剧本杀队长",
			HostCreditScore:  89,
			EventDateTime:    now.Add(24*time.Hour + 19*time.Hour),
			EventLocation:    "上海市虹口区四川北路",
		},
		{
			ID:               "board_6",
			Title:            "《血染钟楼》入门局欢迎萌新",
			Description:      "主持人带规则，预计 2.5 小时，结束后可一起夜宵。",
			CurrentMembers:   6,
			MaxMembers:       10,
			Area:             "BoardGames",
			Tab:              "桌游",
			HardcoreScore:    25,
			HostFaceTraits:   []string{"血染钟楼", "新手友好", "桌游", "夜宵局"},
			InteractionCount: 143,
			LastActiveTime:   now.Add(-8 * time.Hour),
			MatchScore:       48,
			HostNickname:     "钟楼守夜人",
			HostCreditScore:  82,
			EventDateTime:    now.Add(2*24*time.Hour + 20*time.Hour),
			EventLocation:    "上海市闵行区莘庄商圈",
		},
		{
			ID:               "anime_1",
			Title:            "CP30 漫展同行 · 约妆造互拍",
			Description:      "周六全天，已有门票，求同坑 coser 一起逛展打卡。",
			CurrentMembers:   2,
			MaxMembers:       4,
			Area:             "AnimeCon",
			Tab:              "推荐",
			HardcoreScore:    40,
			HostFaceTraits:   []string{"漫展", "cos", "摄影", "互拍"},
			InteractionCount: 628,
			LastActiveTime:   now.Add(-2 * time.Hour),
			MatchScore:       65,
			HostNickname:     "二刺猿日常",
			HostCreditScore:  87,
			EventDateTime:    now.Add(6*24*time.Hour + 9*time.Hour),
			EventLocation:    "杭州市萧山区国际博览中心",
		},
		{
			ID:               "photo_1",
			Title:            "外滩夜景人像约拍",
			Description:      "自带灯棒，返 9 张精修，希望模特有街拍经验。",
			CurrentMembers:   1,
			MaxMembers:       2,
			Area:             "Photo",
			Tab:              "附近",
			HardcoreScore:    50,
			HostFaceTraits:   []string{"摄影", "人像", "夜景", "外滩"},
			InteractionCount: 201,
			LastActiveTime:   now.Add(-14 * time.Hour),
			MatchScore:       42,
			HostNickname:     "快门猎人",
			HostCreditScore:  93,
			EventDateTime:    now.Add(24*time.Hour + 18*time.Hour),
			EventLocation:    "上海市黄浦区中山东一路",
		},
		{
			ID:               "game_1",
			Title:            "王者五排缺辅助 · 星耀局",
			Description:      "语音开黑，不喷人，能保射手，晚上 9 点后在线。",
			CurrentMembers:   4,
			MaxMembers:       5,
			Area:             "Game",
			Tab:              "匹配",
			HardcoreScore:    70,
			HostFaceTraits:   []string{"王者荣耀", "开黑", "星耀", "语音局"},
			InteractionCount: 445,
			LastActiveTime:   now.Add(-20 * time.Minute),
			MatchScore:       58,
			HostNickname:     "野王请带飞",
			HostCreditScore:  85,
			EventDateTime:    now.Add(4 * time.Hour),
			EventLocation:    "线上 · 微信语音",
		},
		{
			ID:               "game_2",
			Title:            "黑神话联机 Boss 互助",
			Description:      "卡关求大佬，也可一起探索隐藏，PC 端 Steam。",
			CurrentMembers:   2,
			MaxMembers:       4,
			Area:             "Game",
			Tab:              "推荐",
			HardcoreScore:    55,
			HostFaceTraits:   []string{"黑神话", "Steam", "联机", "互助"},
			InteractionCount: 892,
			LastActiveTime:   now.Add(-1 * time.Hour),
			MatchScore:       38,
			HostNickname:     "悟空残影",
			HostCreditScore:  90,
			EventDateTime:    now.Add(3 * time.Hour),
			EventLocation:    "线上 · Discord",
		},
		{
			ID:               "travel_1",
			Title:            "清明小长假安吉露营 · 差2人拼车",
			Description:      "自驾上海出发，帐篷可租，会做饭优先，AA 制。",
			CurrentMembers:   4,
			MaxMembers:       6,
			Area:             "Travel",
			Tab:              "附近",
			HardcoreScore:    35,
			HostFaceTraits:   []string{"露营", "自驾", "户外", "拼车"},
			InteractionCount: 278,
			LastActiveTime:   now.Add(-5 * time.Hour),
			MatchScore:       50,
			HostNickname:     "山野旅人",
			HostCreditScore:  86,
			EventDateTime:    now.Add(10*24*time.Hour + 7*time.Hour),
			EventLocation:    "浙江省湖州市安吉县",
		},
		{
			ID:               "study_1",
			Title:            "图书馆自习搭子 · 考研冲刺",
			Description:      "复旦附近，每天 9–18 点，互相监督不看手机。",
			CurrentMembers:   3,
			MaxMembers:       6,
			Area:             "Study",
			Tab:              "推荐",
			HardcoreScore:    80,
			HostFaceTraits:   []string{"自习", "考研", "监督", "安静"},
			InteractionCount: 156,
			LastActiveTime:   now.Add(-10 * time.Hour),
			MatchScore:       33,
			HostNickname:     "早起刷题人",
			HostCreditScore:  88,
			EventDateTime:    now.Add(24*time.Hour + 9*time.Hour),
			EventLocation:    "上海市杨浦区复旦大学周边",
		},
		{
			ID:               "pet_1",
			Title:            "周末遛狗局 · 大型犬友好",
			Description:      "世纪公园晨遛，家有金毛，求同好交流喂养心得。",
			CurrentMembers:   5,
			MaxMembers:       8,
			Area:             "Pet",
			Tab:              "附近",
			HardcoreScore:    15,
			HostFaceTraits:   []string{"宠物", "遛狗", "金毛", "周末晨"},
			InteractionCount: 124,
			LastActiveTime:   now.Add(-2 * 24 * time.Hour),
			MatchScore:       28,
			HostNickname:     "毛孩子家长",
			HostCreditScore:  81,
			EventDateTime:    now.Add(3*24*time.Hour + 7*time.Hour),
			EventLocation:    "上海市浦东新区世纪公园",
		},
		{
			ID:               "music_1",
			Title:            "Livehouse 拼票 · 独立乐队场",
			Description:      "本周五演出，多一张票，一起拼车往返静安。",
			CurrentMembers:   1,
			MaxMembers:       2,
			Area:             "Music",
			Tab:              "推荐",
			HardcoreScore:    30,
			HostFaceTraits:   []string{"livehouse", "独立音乐", "拼票", "周五夜"},
			InteractionCount: 233,
			LastActiveTime:   now.Add(-7 * time.Hour),
			MatchScore:       45,
			HostNickname:     "耳机不离身",
			HostCreditScore:  83,
			EventDateTime:    now.Add(4*24*time.Hour + 20*time.Hour),
			EventLocation:    "上海市静安区 MAO Livehouse",
		},
		{
			ID:               "outdoor_1",
			Title:            "周六徒步九溪 · 休闲线",
			Description:      "约 12km，中等强度，自带水和干粮，下雨顺延。",
			CurrentMembers:   7,
			MaxMembers:       12,
			Area:             "Outdoor",
			Tab:              "附近",
			HardcoreScore:    45,
			HostFaceTraits:   []string{"徒步", "户外", "九溪", "周末"},
			InteractionCount: 389,
			LastActiveTime:   now.Add(-4 * time.Hour),
			MatchScore:       52,
			HostNickname:     "山系青年",
			HostCreditScore:  87,
			EventDateTime:    now.Add(5*24*time.Hour + 8*time.Hour),
			EventLocation:    "杭州市西湖区九溪烟树入口",
		},
		{
			ID:               "drive_1",
			Title:            "虹桥机场接机拼车 · 今晚 22:30",
			Description:      "航班 MU5101，可拼 2 人，行李不多的来。",
			CurrentMembers:   1,
			MaxMembers:       3,
			Area:             "Drive",
			Tab:              "附近",
			HardcoreScore:    20,
			HostFaceTraits:   []string{"拼车", "接机", "虹桥", "今晚"},
			InteractionCount: 67,
			LastActiveTime:   now.Add(-12 * time.Minute),
			MatchScore:       22,
			HostNickname:     "顺风车老司机",
			HostCreditScore:  79,
			EventDateTime:    now.Add(8 * time.Hour),
			EventLocation:    "上海虹桥国际机场 T2",
		},
		{
			ID:               "food_2",
			Title:            "深夜火锅局 · 缺2人",
			Description:      "重庆牛油锅底，能吃辣的来，人均约 120。",
			CurrentMembers:   4,
			MaxMembers:       6,
			Area:             "Food",
			Tab:              "推荐",
			HardcoreScore:    25,
			HostFaceTraits:   []string{"火锅", "夜宵", "辣", "拼桌"},
			InteractionCount: 334,
			LastActiveTime:   now.Add(-2 * time.Hour),
			MatchScore:       61,
			HostNickname:     "无辣不欢",
			HostCreditScore:  84,
			EventDateTime:    now.Add(5 * time.Hour),
			EventLocation:    "上海市长宁区中山公园龙之梦附近",
		},
		{
			ID:               "sport_2",
			Title:            "羽毛球双打 · 中级水平",
			Description:      "静安体育馆订场 2 小时，自带拍，求固定搭子。",
			CurrentMembers:   2,
			MaxMembers:       4,
			Area:             "Sport",
			Tab:              "匹配",
			HardcoreScore:    65,
			HostFaceTraits:   []string{"羽毛球", "双打", "运动", "中级"},
			InteractionCount: 198,
			LastActiveTime:   now.Add(-18 * time.Hour),
			MatchScore:       47,
			HostNickname:     "羽球小张",
			HostCreditScore:  86,
			EventDateTime:    now.Add(2*24*time.Hour + 14*time.Hour),
			EventLocation:    "上海市静安区羽毛球馆",
		},
		{
			ID:               "sport_3",
			Title:            "晨跑 5km · 徐汇滨江",
			Description:      "配速 6 分左右，跑完一起喝咖啡，新手也可跟跑。",
			CurrentMembers:   3,
			MaxMembers:       8,
			Area:             "Sport",
			Tab:              "附近",
			HardcoreScore:    30,
			HostFaceTraits:   []string{"跑步", "晨跑", "滨江", "咖啡局"},
			InteractionCount: 112,
			LastActiveTime:   now.Add(-22 * time.Hour),
			MatchScore:       36,
			HostNickname:     "早起跑者",
			HostCreditScore:  80,
			EventDateTime:    now.Add(24*time.Hour + 6*time.Hour),
			EventLocation:    "上海市徐汇区徐汇滨江绿道",
		},
		{
			ID:               "other_1",
			Title:            "同城读书会 · 《被讨厌的勇气》",
			Description:      "线下分享 1 小时，限 8 人，需提前读完前三章。",
			CurrentMembers:   6,
			MaxMembers:       8,
			Area:             "Other",
			Tab:              "推荐",
			HardcoreScore:    40,
			HostFaceTraits:   []string{"读书会", "心理学", "线下", "分享"},
			InteractionCount: 89,
			LastActiveTime:   now.Add(-24 * time.Hour),
			MatchScore:       30,
			HostNickname:     "书虫阿宁",
			HostCreditScore:  85,
			EventDateTime:    now.Add(7*24*time.Hour + 15*time.Hour),
			EventLocation:    "上海市黄浦区思南公馆附近咖啡馆",
		},
	}
}
