package seed

import (
	"time"

	"matchit/backend/api/internal/model"
)

// Posts 与 Flutter mockPosts 对齐，便于 POST /api/v1/seed 一键导入
func Posts(now time.Time) []model.MatchPost {
	return []model.MatchPost{
		{
			ID:               "board_official_1",
			Title:            "【官方】MATCHit 桌游嘉年华 · 本周末",
			Description:      "平台官方活动，多桌游同场，报名即送周边。",
			CurrentMembers:   12,
			MaxMembers:       30,
			Area:             "BoardGames",
			Tab:              "推荐",
			HardcoreScore:    55,
			HostFaceTraits:   []string{"策略思维", "桌游爱好者", "社交型", "平衡型"},
			InteractionCount: 890,
			LastActiveTime:   now.Add(-1 * time.Hour),
			MatchScore:       78,
			HostNickname:     "MATCHit 官方",
			HostCreditScore:  99,
			EventDateTime:    now.Add(2*24*time.Hour + 14*time.Hour),
			EventLocation:    "上海市徐汇区 MATCHit 体验中心",
			IsPinned:         true,
			PinPriority:      100,
		},
		{
			ID:               "board_1",
			Title:            "周六下午寻找《阿瓦隆》大神局",
			Description:      "想约一组 5 人局，必须是硬核老手。",
			CurrentMembers:   3,
			MaxMembers:       5,
			Area:             "BoardGames",
			Tab:              "推荐",
			HardcoreScore:    95,
			HostFaceTraits:   []string{"策略思维", "硬核派", "逻辑型", "竞争意识"},
			InteractionCount: 420,
			LastActiveTime:   now.Add(-6 * time.Hour),
			MatchScore:       40,
			HostNickname:     "阿瓦隆老司机",
			HostCreditScore:  92,
			EventDateTime:    now.Add(24*time.Hour + 15*time.Hour),
			EventLocation:    "上海市长宁区桌游吧 · 愚园路店",
		},
		{
			ID:               "board_2",
			Title:            "周五晚桌游《卡坦》进阶局",
			Description:      "熟悉规则，氛围轻松。",
			CurrentMembers:   2,
			MaxMembers:       4,
			Area:             "BoardGames",
			Tab:              "桌游",
			HardcoreScore:    55,
			HostFaceTraits:   []string{"策略思维", "桌游爱好者", "平衡型", "团队配合"},
			InteractionCount: 256,
			LastActiveTime:   now.Add(-12 * time.Hour),
			MatchScore:       60,
			HostNickname:     "卡坦岛民",
			HostCreditScore:  86,
			EventDateTime:    now.Add(3*24*time.Hour + 19*time.Hour),
			EventLocation:    "上海市静安区社区活动中心 3F",
		},
		{
			ID:               "board_3",
			Title:            "周五晚桌游《卡坦》新手局",
			Description:      "新朋友优先，氛围轻松，地点靠近地铁站。",
			CurrentMembers:   2,
			MaxMembers:       4,
			Area:             "BoardGames",
			Tab:              "桌游",
			HardcoreScore:    20,
			HostFaceTraits:   []string{"桌游爱好者", "休闲派", "社交型", "慢节奏"},
			InteractionCount: 98,
			LastActiveTime:   now.Add(-3 * 24 * time.Hour),
			MatchScore:       20,
			HostNickname:     "慢热桌游君",
			HostCreditScore:  78,
			EventDateTime:    now.Add(4*24*time.Hour + 20*time.Hour),
			EventLocation:    "上海市普陀区金沙江路地铁站附近",
		},
		{
			ID:               "food_1",
			Title:            "周末附近美食探店拼餐",
			Description:      "想找 4 人拼餐，吃遍市区新开餐厅。",
			CurrentMembers:   3,
			MaxMembers:       4,
			Area:             "Food",
			Tab:              "附近",
			HardcoreScore:    30,
			HostFaceTraits:   []string{"美食探索", "社交型", "慢节奏", "拍照打卡"},
			InteractionCount: 180,
			LastActiveTime:   now.Add(-20 * time.Hour),
			MatchScore:       35,
			HostNickname:     "吃货小分队",
			HostCreditScore:  84,
			EventDateTime:    now.Add(2*24*time.Hour + 12*time.Hour),
			EventLocation:    "上海市黄浦区新天地商圈",
		},
		{
			ID:               "sport_1",
			Title:            "周日早晨街头篮球 3v3",
			Description:      "附近友邻一起玩，装备齐全，轻松娱乐。欢迎热爱运动的你加入。",
			CurrentMembers:   5,
			MaxMembers:       5,
			Area:             "Sport",
			Tab:              "附近",
			HardcoreScore:    40,
			HostFaceTraits:   []string{"运动达人", "活力型", "竞争意识", "早起党"},
			InteractionCount: 310,
			LastActiveTime:   now.Add(-24 * time.Hour),
			MatchScore:       25,
			HostNickname:     "球场老炮",
			HostCreditScore:  88,
			EventDateTime:    now.Add(5*24*time.Hour + 8*time.Hour),
			EventLocation:    "上海市浦东新区张江社区篮球场",
		},
	}
}
